### ISSUE TITLE
Stavba - podvozek - krok 2, 3 - přefotit

### ISSUE THREAD

**Issue by JakubAndrysek** [RoboticsBrno/roboruka.robotickytabor.cz#19]
Je potřeba přefotit krok 2 a 3, protože nesedí zámečky na zámečky a díry na díry. Nutno zvíraznit v návodu. Chybné foto je pouze v techto dvou krocích.

**Comment by renata7zemanova** [comment]
ecfab7c145e241f37d76fd883d4da5b15f1f03a1
