### ISSUE TITLE
Kompletace ruky chybi

### ISSUE THREAD

**Issue by lavirlifiliol** [RoboticsBrno/roboruka.robotickytabor.cz#35]
Po návodu na klepeta je foto hotové ruky, ale postup podle kroků v návodu k takovému výsledku nevede.

**Comment by lavirlifiliol** [comment]
Correction: on PC the final step of the hand tutorial is before the tutorial itself, at 78, with the guide starting at 82

**Comment by MarPta** [comment]
It is for servo id description purposes. Bottom note of figure now mentions that fact.
